// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.Nodeinfo":       schema_pkg_apis_aci_v1_Nodeinfo(ref),
		"github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoSpec":   schema_pkg_apis_aci_v1_NodeinfoSpec(ref),
		"github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoStatus": schema_pkg_apis_aci_v1_NodeinfoStatus(ref),
	}
}

func schema_pkg_apis_aci_v1_Nodeinfo(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Nodeinfo is the Schema for the nodeinfos API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoSpec", "github.com/gaurav-dalvi/nodeinfo-operator/pkg/apis/aci/v1.NodeinfoStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_aci_v1_NodeinfoSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeinfoSpec defines the desired state of Nodeinfo",
				Properties: map[string]spec.Schema{
					"nodename": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"macaddress": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"nodename", "macaddress"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_aci_v1_NodeinfoStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeinfoStatus defines the observed state of Nodeinfo",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
